#!/bin/bash

#$


if [ $# -lt 1 ]
then
echo "Brak argumentów"
fi

if [[ -f $1 ]]
then
cat $1 | awk '{ gsub(/[\.\?\!]\s/, ".\n"); print }' | awk 'BEGIN { FS = "."; RS = "\n" } /[A-Z].*\.$/ { cnt++; print $(NF-1) } END {print cnt}'

fi
